services:
  web:
    container_name: croma-web
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jdbc
    volumes:
      - jdbc-local-pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - jdbc-pgadmin-data:/var/lib/pgadmin
volumes:
  jdbc-local-pgdata:
  jdbc-pgadmin-data:
